language: python

install:
    - pip install -e .

matrix:
    include:
        - os: linux
          python: 3.8

script:
    - python -m unittest -v tests/test_basic.py
    - python -m unittest -v tests/test_task_order.py
    - python -m unittest -v tests/test_task_timeout.py
